### ISSUE TITLE
Make Journals property names configurable

### ISSUE THREAD

**Issue by N4M3Z** [srg-kostyrko/obsidian-journal#87]
Currently, the plugin defaults to using the following properties:
```yaml
journal: journal
journal-end-date: 2024-12-24
journal-section: day
journal-start-date: 2024-12-24
```
It would be good if the names of the properties could be customized so that they can be tailored to your users' frontmatter schemes. E.g. I have properties in my notes like `date-start` that would already satisfy the `journal-start-date` property as it has the same value.
